In [318]:
import pandas as pd
import numpy as np
import sys
import os

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [313]:
def MD(x):
    n=len(x)
    y=np.array(x)
    mean=np.mean(y, axis=0)
#     print("mean of each dimension")
#     print(mean)
#     print("")
    for x in y:
        z=y-mean
    #print("deviation matrix")
    #print(z)
    k=z.T
    #print(k.shape)
    t=np.matmul(k, z)/(n-1)
#     print("co-variance matrix")
#     print(t)
#     print("inverse covariance matrix")
    p = np.linalg.inv(t)
#     print(p)
    return p,mean

In [314]:
def medv(covar,mean,v):
    vect=np.array(v)
    vect=vect-mean;
    
    vectt=np.array(vect.T)
   
    z=np.matmul(vectt,covar)
    return np.sqrt(np.matmul(z,vect)*0.5)

In [315]:
def predict(incovar,mean_c,y,pwi):
    dis=[]

    for i  in range(3):
        dis.append(medv(incovar[i],mean_c[i],y))
    res=[]
    res=np.log(pwi)-dis
    res=list(res)
    return res.index(max(res))
    

In [331]:
def NB(data):
    data.head()
    data['species']=data["species"].astype("category")
    data['species']=data["species"].cat.codes
    X=data
    y=data.iloc[:,-1]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)
    df[0]=(X_train[X_train["species"]==0])
    df[1]=(X_train[X_train["species"]==1])
    df[2]=(X_train[X_train["species"]==2])
    df[0]=df[0].iloc[:,:-1]
    df[1]=df[1].iloc[:,:-1]
    df[2]=df[2].iloc[:,:-1]
    pwi=[]
    for i  in range(3):
        pwi.append(len(df[i])/(len(df[0])+len(df[1])+len(df[2])))
    X_test=X_test.iloc[:,:-1]
    X_test=X_test.values
    incovar=[]
    mean_c=[]
    for i in range(3):
        covar,mean=MD(df[i])
        incovar.append(covar)
        mean_c.append(mean)
    y_pred=[]
    for i in range(len(X_test)):
           y_pred.append(predict(incovar,mean_c,X_test[i],pwi))
    return y_pred

In [332]:
data=pd.read_csv("IRIS.csv")


In [333]:
y_pred=NB(data)

In [335]:
accuracy_score(y_pred,y_test)

0.98

In [340]:

for i in range(3):
    print("inv covariance matrix of each class "+ str(i))
    print(incovar[i])
    print("")

inv covariance matrix of each class 0
[[ 17.5108862  -10.8996166   -3.3076713   -6.96844916]
 [-10.8996166   13.81534612  -0.85567388  -2.28486839]
 [ -3.3076713   -0.85567388  56.35280943 -23.50823568]
 [ -6.96844916  -2.28486839 -23.50823568 129.20215515]]

inv covariance matrix of each class 1
[[ 11.42928589  -3.11344839 -11.18471712   6.83505858]
 [ -3.11344839  15.44526866   1.53471281 -12.22931609]
 [-11.18471712   1.53471281  23.66592834 -29.79628782]
 [  6.83505858 -12.22931609 -29.79628782  82.1481057 ]]

inv covariance matrix of each class 2
[[ 12.29544664  -3.43766766 -12.61466355   2.67163196]
 [ -3.43766766  13.7830845    1.59137505  -7.07419201]
 [-12.61466355   1.59137505  16.66838174  -5.15047318]
 [  2.67163196  -7.07419201  -5.15047318  23.94130465]]



50