In [3]:
from scipy.spatial import distance
import numpy as np

In [4]:
def MD(x):
    n=len(x)
    y=np.array(x)
    mean=np.mean(y, axis=0)
    print("mean of each dimension")
    print(mean)
    print("")
    for x in y:
        z=y-mean
    #print("deviation matrix")
    #print(z)
    k=z.T
    #print(k.shape)
    t=np.matmul(k, z)/(n-1)
    print("co-variance matrix")
    print(t)
    #print("inverse covariance matrix")
    p = np.linalg.inv(t)
    #print(p)
    return p,mean
    
    

In [5]:
def medv(covar,mean,v):
    vect=np.array(v)
    vect=vect-mean;
    
    vectt=np.array(vect.T)
   
    z=np.matmul(vectt,covar)
    return np.sqrt(np.matmul(z,vect))

In [15]:
x=[[64,580,29],
   [66,570,33],
   [68,590,37],
   [69,660,46],
   [73,600,55]
  ]

In [16]:
print(len(x))
covarin,mean=MD(x)

5
mean of each dimension
[ 68. 600.  40.]

co-variance matrix
[[  11.5    50.     34.75]
 [  50.   1250.    205.  ]
 [  34.75  205.    110.  ]]


In [8]:
d=medv(covarin,mean,[66,640,44])

In [9]:
d

5.334540488762537

In [10]:
#inputs
x=[[28,31,130.0,68.12],
   [24,28,143.0,127.89],
   [28,20,136.0,89.03],
   [32,34,130.5,78.28],
   [22,15, 125.0, 134.08],
   [26,37,147.5,135.31],
   [24 ,19 ,135.0 ,130.48],
   [28 ,22 ,125.0,86.48],
    [24,26,127.0,129.47],
   [30,21 ,139.0,82.43],
  [22,20,121.5,127.41],
  [30,38,150.5,71.21],
  [24,17 ,120.0, 132.06],
  [26,20,125.0,90.85]]
v=[[30 ,20, 133, 189.6]
,[22 ,30 ,100.06 ,126.0075]
,[28.47 ,20.11, 133.06, 188.90]]


In [11]:
covarin,mean=MD(x)
d=[]
print("")
print("inverse covariance matrix")
print(covarin)



mean of each dimension
[ 26.28571429  24.85714286 132.5        105.93571429]

co-variance matrix
[[  9.75824176  12.81318681  12.07692308 -72.15406593]
 [ 12.81318681  56.9010989   49.11538462 -70.62065934]
 [ 12.07692308  49.11538462  92.80769231 -46.06961538]
 [-72.15406593 -70.62065934 -46.06961538 714.00118022]]

inverse covariance matrix
[[ 0.58465881 -0.04194565 -0.02749362  0.0531605 ]
 [-0.04194565  0.03896147 -0.01585996 -0.00140858]
 [-0.02749362 -0.01585996  0.02126939 -0.00297471]
 [ 0.0531605  -0.00140858 -0.00297471  0.00644149]]


In [12]:
for i in range (3):
    d.append(medv(covarin,mean,v[i]))

In [13]:
d

[9.46059352152669, 5.5389941702554735, 8.30654313092512]

In [14]:
print(min(d))

5.5389941702554735
